#!/bin/bash

# Define variables
SERVICE_NAME="oligomer_container"
IMAGE_NAME="localhost/oligomer_app"
CONTAINER_NAME="oligomer_container"
CONTAINER_PORT="8000"

# Create the systemd unit file
cat <<EOF | sudo tee /etc/systemd/system/$SERVICE_NAME.service > /dev/null
[Unit]
Description=Oligomer Container
After=network.target

[Service]
Restart=always
ExecStop=/usr/bin/podman stop -t 10 $CONTAINER_NAME
ExecStopPost=/usr/bin/podman rm -f $CONTAINER_NAME
ExecStart=/usr/bin/podman run --name $CONTAINER_NAME --rm -p $CONTAINER_PORT:8000 $IMAGE_NAME

[Install]
WantedBy=multi-user.target
EOF

# Reload systemd configuration
sudo systemctl daemon-reload

# Enable and start the service
sudo systemctl enable $SERVICE_NAME.service
sudo systemctl start $SERVICE_NAME.service

# Check the status of the service
sudo systemctl status $SERVICE_NAME.service
